# Generated by Django 3.2.13 on 2023-12-18 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='monthly_price',
        ),
        migrations.AddField(
            model_name='product',
            name='yearly_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
