# Generated by Django 3.2.13 on 2023-05-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainings',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
