# Generated by Django 3.2.13 on 2023-12-01 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_projects_project_initiator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='deal_picture',
        ),
        migrations.CreateModel(
            name='DealImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='deals/deals.jpeg', upload_to='deals/', verbose_name='Supporting Documents')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deals')),
            ],
        ),
    ]
