# Generated by Django 3.2.13 on 2023-12-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231218_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetechnic',
            name='Technical_factors',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='This include climate,season, soil preparation,seeds, semis, care, conditions, and protection'),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='harvest_factors',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Include how to harvest, post harvest conditioning, yield'),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='industrialization_factors',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='what to consider if industrializing'),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='other_factors',
            field=models.TextField(blank=True, max_length=2100, null=True, verbose_name='Import Export opportunities, main producers, main consumers...'),
        ),
    ]
