# Generated by Django 3.2.13 on 2024-01-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240114_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='categories',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='core.category'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Email Address'),
        ),
    ]
