# Generated by Django 3.2.13 on 2023-12-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231219_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichetechnic',
            name='Technical_factors',
            field=models.TextField(blank=True, max_length=4500, null=True, verbose_name='This include climate,season, soil preparation,seeds, semis, care, conditions, and protection'),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='description',
            field=models.TextField(max_length=4500),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='harvest_factors',
            field=models.TextField(blank=True, max_length=4500, null=True, verbose_name='Include how to harvest, post harvest conditioning, yield'),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='industrialization_factors',
            field=models.TextField(blank=True, max_length=4500, null=True, verbose_name='what to consider if industrializing'),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='marketing_factor',
            field=models.TextField(blank=True, max_length=4500, null=True, verbose_name='include seed supplier, equipment cost, storage requirements, average price per unit (acre, kilo, tone...), average cost '),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='other_factors',
            field=models.TextField(blank=True, max_length=5100, null=True, verbose_name='Import Export opportunities, main producers, main consumers...'),
        ),
        migrations.AlterField(
            model_name='fichetechnic',
            name='principal_risks',
            field=models.TextField(blank=True, max_length=3368, null=True),
        ),
    ]
