# Generated by Django 3.2.13 on 2023-05-29 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cost_trainings_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingapplication',
            old_name='company',
            new_name='company_name',
        ),
    ]
