# Generated by Django 3.2.13 on 2023-12-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20231201_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='final_decision',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('REJECTED', 'REJECTED')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='blog_pics/blog 1.pnp', upload_to='blog_pics/'),
        ),
    ]
