# Generated by Django 3.2.13 on 2023-12-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231219_1655'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-monthly_price',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
