# Generated by Django 3.2.13 on 2023-05-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_company_trainingapplication_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingapplication',
            name='letter',
        ),
    ]
