# Generated by Django 3.2.13 on 2023-12-06 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20231206_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deals',
            name='deal_category',
        ),
    ]
