# Generated by Django 3.2.13 on 2023-05-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_trainingapplication_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='training_days',
            field=models.CharField(choices=[('MONDAY', 'MONDAY'), ('TUESDAY', 'TUESDAY'), ('WEDNESDAY', 'WEDNESDAY'), ('THURSDAY', 'THURSDAY'), ('FRIDAY', 'FRIDAY'), ('SATURDAY', 'SATURDAY')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='trainingapplication',
            name='position',
            field=models.CharField(choices=[('OFFICER', 'OFFICER'), ('ASSISTANT VICE PRESIDENT', 'ASSISTANT VICE PRESIDENT'), ('VICE PRESIDENT', 'VICE PRESIDENT'), ('OTHER', 'OTHER')], max_length=30),
        ),
    ]
