# Generated by Django 3.2.13 on 2023-12-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20231220_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogread',
            old_name='user',
            new_name='reader',
        ),
        migrations.AlterUniqueTogether(
            name='blogread',
            unique_together={('reader', 'blog_post')},
        ),
    ]
