# Generated by Django 3.2.13 on 2023-05-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230529_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainings',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainings',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainings',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainings',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainings',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
    ]
