# Generated by Django 3.2.13 on 2023-12-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_project_dealimages_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdeals',
            name='product_image',
        ),
        migrations.CreateModel(
            name='ProductDealImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='deals/deals.jpeg', upload_to='deals/', verbose_name='Supporting Documents')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productdeals')),
            ],
        ),
    ]
