# Generated by Django 3.2.13 on 2023-12-20 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20231220_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDealRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_deal_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productdeals')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reader', 'product_deal_read')},
            },
        ),
        migrations.CreateModel(
            name='DealRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deal_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.deals')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reader', 'deal_read')},
            },
        ),
    ]
