# Generated by Django 3.2.13 on 2023-05-29 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230529_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainings',
            name='training_days',
        ),
    ]
