# Generated by Django 3.2.13 on 2023-12-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dealread_productdealread'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdeals',
            name='product_deal_title',
            field=models.CharField(default='computers deal available', max_length=100),
            preserve_default=False,
        ),
    ]
