# Generated by Django 3.2.13 on 2023-12-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20231217_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='pricing',
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=5),
            preserve_default=False,
        ),
    ]
