# Generated by Django 3.2.13 on 2023-06-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_trainings_training_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainings',
            name='duration',
            field=models.CharField(choices=[('0:30 PER DAY', '0:30 PER DAY'), ('0:45 PER DAY', '0:45 PER DAY'), ('1:00 PER DAY', '1:00 PER DAY'), ('1:30 PER DAY', '1:30 PER DAY'), ('1:45 PER DAY', '1:45 PER DAY'), ('2:00 PER DAY', '2:00 PER DAY'), ('2:30 PER DAY', '2:30 PER DAY'), ('2:45 PER DAY', '2:45 PER DAY'), ('3:00 PER DAY', '3:00 PER DAY')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='trainings',
            name='training_mode',
            field=models.CharField(choices=[('ONLINE', 'ONLINE'), ('IN PERSON', 'IN PERSON'), ('HYBRID', 'HYBRID')], default='', max_length=20),
        ),
    ]
