# Generated by Django 3.2.13 on 2023-12-20 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productdeals_product_deal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='deal_type',
            field=models.CharField(choices=[('Looking for Financing Provider', 'Looking for Financing Provider'), ('Offering Services', 'Offering Services'), ('In Search of Services Provider', 'In Search of Services Provider'), ('Offering Financing', 'Offering Financing'), ('Offering Leadership Services', 'Offering Leadership Services'), ('In Search of Leadership Services Provider', 'In Search of Leadership Services Provider'), ('Offering Management Services', 'Offering Management Services'), ('In Search of Management Services Provider', 'In Search of Management Services Provider'), ('In Search of Technical Partner', 'In Search of Technical Partner'), ('Offering Technical Services', 'Offering Technical Services')], default='', max_length=50),
        ),
        migrations.CreateModel(
            name='FicheRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fiche_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fichetechnic')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reader', 'fiche_read')},
            },
        ),
    ]
