# Generated by Django 3.2.13 on 2023-06-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230603_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='deal_picture',
            field=models.FileField(blank=True, null=True, upload_to='deals/'),
        ),
    ]
