# Generated by Django 3.2.13 on 2023-06-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_deals_deal_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='image',
            new_name='blog_image',
        ),
        migrations.AlterField(
            model_name='deals',
            name='deal_picture',
            field=models.FileField(blank=True, null=True, upload_to='deals/', verbose_name='Supporting Documents'),
        ),
    ]
