# Generated by Django 3.2.13 on 2023-12-20 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20231220_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobs')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('reader', 'job_read')},
            },
        ),
    ]
