# Generated by Django 3.2.13 on 2023-12-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_jobread'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogread',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='dealread',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='jobread',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='productdealread',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
