# Generated by Django 3.2.13 on 2023-06-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230607_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(default='blog_pics/blogs.pnp', upload_to='blog_pics'),
        ),
    ]
