# Generated by Django 3.2.13 on 2023-12-21 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20231221_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
