# Generated by Django 3.2.13 on 2023-12-21 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_employeeprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='hired_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
