# Generated by Django 3.2.13 on 2023-07-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonies',
            name='user_pic',
            field=models.ImageField(default='blog_pics/person_icon 1.png', upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='prof_pic',
            field=models.ImageField(default='blog_pics/person_icon 1.png', upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='prof_pic',
            field=models.ImageField(default='blog_pics/person_icon 1.png', upload_to='employee_pictures/'),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='prof_pic',
            field=models.ImageField(default='blog_pics/person_icon 1.png', upload_to='document/'),
        ),
        migrations.AlterField(
            model_name='experts',
            name='prof_pic',
            field=models.ImageField(default='blog_pics/person_icon 1.png', upload_to='document/'),
        ),
    ]
