# Generated by Django 3.2.13 on 2023-07-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230718_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprises',
            name='company_id',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enterprises',
            name='registration_date',
            field=models.DateField(null=True),
        ),
    ]
